version: '2'
services:
  chat:
    build: ./chat-service
    ports:
      - "8123:8123"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
  db:
    build: ./mysql-service
    ports:
      - "3306:3306"